In [41]:
import numpy as np

a = np.array([0,1,2,3,4,5,6,7,8,9])
print("array({})".format(a))

b = np.array([0])
for i in range(1,10):
    a = np.array([i])
    b = np.append(b,a)
print("array({})".format(b))

c = np.array([0], dtype = 'int64')
for i in range(1,10):
    if i % 2 == 0:
        a = np.array([i])
        c = np.append(c,a)
print("array({})".format(c))

array([0 1 2 3 4 5 6 7 8 9])
array([0 1 2 3 4 5 6 7 8 9])
array([0 2 4 6 8])


In [42]:
print("c.shape = ",c.shape)
print("c.ndim  = ",c.ndim)
print("c.dtype = ",c.dtype)
print("c.size = ",c.size)
print("c.itemsize = ",c.itemsize)

c.shape =  (5,)
c.ndim  =  1
c.dtype =  int64
c.size =  5
c.itemsize =  8


In [48]:
a = np.array([23,45,67,7,2,30,34,82])
print("a = array({})".format(a))
print('최댓값 : ',a.max())
print('최솟값: ',a.min())
print("평균 : ",a.mean())

a = array([23 45 67  7  2 30 34 82])
최댓값 :  82
최솟값:  2
평균 :  36.25


In [49]:
b = np.random.randint(0,99, size = 10)
print("b = array({})".format(b))
print('최댓값 : ',b.max())
print('최솟값: ',b.min())
print("평균 : ",b.mean())

b = array([ 2 22 29 63 13  6 57 97 40 63])
최댓값 :  97
최솟값:  2
평균 :  39.2


In [50]:
c = np.append(a,b)
print("c = ",c)

c =  [23 45 67  7  2 30 34 82  2 22 29 63 13  6 57 97 40 63]


In [58]:
a = np.array([[1,2,3],[4,5,6],[7,8,9]])
print("a =",a)
b = np.array([[2,2,2],[2,2,2],[2,2,2]])
print("b =",b)

print("a+b =",a+b)
print("a-b =",a-b)
print("a*b =",a*b)
print("a/b =",a/b)
print("a@b =",a@b)
print("a**2 =",a**2)


a = [[1 2 3]
 [4 5 6]
 [7 8 9]]
b = [[2 2 2]
 [2 2 2]
 [2 2 2]]
a+b = [[ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]
a-b = [[-1  0  1]
 [ 2  3  4]
 [ 5  6  7]]
a*b = [[ 2  4  6]
 [ 8 10 12]
 [14 16 18]]
a/b = [[0.5 1.  1.5]
 [2.  2.5 3. ]
 [3.5 4.  4.5]]
a@b = [[12 12 12]
 [30 30 30]
 [48 48 48]]
a**2 = [[ 1  4  9]
 [16 25 36]
 [49 64 81]]


In [76]:
a1 = np.full((3,3),2)
print("a1 =", a1)

a2 = np.arange(1,13)
print("a2 =",a2)

a3 = np.arange(3,51,3)
print("a3 =",a3)

a4 = np.linspace(0,20,5)
print("a4=",a4)

a1 = [[2 2 2]
 [2 2 2]
 [2 2 2]]
a2 = [ 1  2  3  4  5  6  7  8  9 10 11 12]
a3 = [ 3  6  9 12 15 18 21 24 27 30 33 36 39 42 45 48]
a4= [ 0.  5. 10. 15. 20.]


In [83]:
a1 = np.arange(1,13).reshape(2,6)
print("a1 =",a1)

a2 = np.arange(1,31).reshape(3,10)
print("a2 =",a2)
a3 = a2.reshape(6,5)
print("a3 =",a3)
a4 = np.transpose(a3)
print("a4 =",a4)

a1 = [[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]]
a2 = [[ 1  2  3  4  5  6  7  8  9 10]
 [11 12 13 14 15 16 17 18 19 20]
 [21 22 23 24 25 26 27 28 29 30]]
a3 = [[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]
 [26 27 28 29 30]]
a4 = [[ 1  6 11 16 21 26]
 [ 2  7 12 17 22 27]
 [ 3  8 13 18 23 28]
 [ 4  9 14 19 24 29]
 [ 5 10 15 20 25 30]]


In [89]:
a = np.random.randint(1,101,size = 15).reshape(3,5)
print("a =",a)
print("a의 열방향 최댓값 :",a.max(axis = 0))
print("a의 열방향 최솟값 :",a.min(axis = 0))
print("a의 열방향 평균  :",a.mean(axis = 0))
print("")
print("a의 행방향 최댓값 :",a.max(axis = 1))
print("a의 행방향 최솟값 :",a.min(axis = 1))
print("a의 행방향 평균  :",a.mean(axis = 1))

a = [[82 86 89 59 34]
 [70 72  2 19 54]
 [33 11 35 75 10]]
a의 열방향 최댓값 : [82 86 89 75 54]
a의 열방향 최솟값 : [33 11  2 19 10]
a의 열방향 평균  : [61.66666667 56.33333333 42.         51.         32.66666667]

a의 행방향 최댓값 : [89 72 75]
a의 행방향 최솟값 : [34  2 10]
a의 행방향 평균  : [70.  43.4 32.8]


In [97]:
a = np.array([1,2,3,4,5,6,7,8,9,10])
print("a = ",a)
b = a[1::2]
print("b =",b)

b = a[5:]
print("b =",b)

c = a[6:]
print("c =",c)

d = a[0:3]
print("d =",d)

e = a[0::2]
print("e =",e)

f = a[::-2]
print("f =",f)

a =  [ 1  2  3  4  5  6  7  8  9 10]
b = [ 2  4  6  8 10]
b = [ 6  7  8  9 10]
c = [ 7  8  9 10]
d = [1 2 3]
e = [1 3 5 7 9]
f = [10  8  6  4  2]


In [2]:
import numpy as np
a = np.arange(0,24).reshape(4,3,2)
print('{:13s}{:5s}'.format('index','element'))
for i in np.ndindex(a.shape):
    print("{}{:7d}".format(i,a[i]))

index        element
(0, 0, 0)      0
(0, 0, 1)      1
(0, 1, 0)      2
(0, 1, 1)      3
(0, 2, 0)      4
(0, 2, 1)      5
(1, 0, 0)      6
(1, 0, 1)      7
(1, 1, 0)      8
(1, 1, 1)      9
(1, 2, 0)     10
(1, 2, 1)     11
(2, 0, 0)     12
(2, 0, 1)     13
(2, 1, 0)     14
(2, 1, 1)     15
(2, 2, 0)     16
(2, 2, 1)     17
(3, 0, 0)     18
(3, 0, 1)     19
(3, 1, 0)     20
(3, 1, 1)     21
(3, 2, 0)     22
(3, 2, 1)     23


In [118]:
a = np.arange(0,24).reshape(4,3,2)
print("array({})".format(np.concatenate((a[0,0],a[1,0]), axis = 0)))

print("array({})".format(np.concatenate((a[0,0],a[2,1]), axis = 0)))

print("array({})".format(np.concatenate((a[0],a[1]), axis = 0)))

print("array({})".format(np.concatenate((a[0],a[1]), axis = 1)))

array([0 1 6 7])
array([ 0  1 14 15])
array([[ 0  1]
 [ 2  3]
 [ 4  5]
 [ 6  7]
 [ 8  9]
 [10 11]])
array([[ 0  1  6  7]
 [ 2  3  8  9]
 [ 4  5 10 11]])


In [130]:
a = np.arange(0,16).reshape(4,4)

b = a[0:,1]
print("b =",b)

c = a[2,1:]
print("c =",c)

d = a[:2,:2]
print("d =",d)

e = a[1:3,1:3]
print("e =",e)

a = a.flatten()

f = a[:7]
print("f =",f)

g = a[8:]
print("g =",g)

h = np.concatenate((a[5:8],a[13:]))
print("h =",h)

b = [ 1  5  9 13]
c = [ 9 10 11]
d = [[0 1]
 [4 5]]
e = [[ 5  6]
 [ 9 10]]
f = [0 1 2 3 4 5 6]
g = [ 8  9 10 11 12 13 14 15]
h = [ 5  6  7 13 14 15]


In [5]:
a = np.array([[1,1,-1],[2,-1,3],[1,2,1]])
b = np.array([0,9,8])
x = np.linalg.solve(a,b)
print("x = {:4.1f} , y ={:4.1f} , z ={:4.1f}".format(x[0],x[1],x[2]))

A = np.array([[1,1,-1],[2,-1,3],[1,2,1]], dtype = 'int32')
print("det(A) ={:4.1f}".format(np.linalg.det(A)))

a1 = np.array([[-1,3],[2,1]])
a2 = np.array([[2,3],[1,1]])
a3 = np.array([[2,-1],[1,2]])
det = 1*np.linalg.det(a1)-1*np.linalg.det(a2)-1*np.linalg.det(a3)
print('det(A) = {:4.1f}'.format(det))

x =  1.0 , y = 2.0 , z = 3.0
det(A) =-11.0
det(A) = -11.0


In [5]:
import numpy as np
a = np.array([0,0,0,0,0,0,0,0,0,0])
print("a = ",a)
b = np.zeros(10) #배열의 초기값을 0으로 생성해주는 메소드이다.
print("b = ",b)
print(type(a))
print(type(b))

a =  [0 0 0 0 0 0 0 0 0 0]
b =  [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
<class 'numpy.ndarray'>
<class 'numpy.ndarray'>


In [11]:
n_arr = np.array([1,2,3,4,5,6,7,8,9,10],dtype = 'int32')
print("n_arr의 크기: ",n_arr.itemsize*n_arr.size) #itemsize는 배열 내의 원소의 크기를 바이트로 나타내고 size은 배열의 원소의 개수를 나타낸다.
n_arr.dtype = 'int64'
print("n_arr의 크기: ",n_arr.itemsize*n_arr.size)
n = np.array([1.5,2.2,3.2,4.9],dtype = 'float64')
print("n의 크기: ",n.itemsize*n.size)

n_arr의 크기:  40
n_arr의 크기:  40
n의 크기:  32


In [14]:
n = np.arange(1,17).reshape(4,4) #arange메소드를활용하여 1~16까지의 1차원 배열을 생성한 후 reshape메소드를 활용하여 4,4의 2차원 배열로 만든다.
print(n)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]


In [19]:

a = np.random.random(size = 10) #크기가 10이고 배열 원소들의 값은 난수 값으로 생성한다
print("a =",a)
print("최댓값 : ",a.max())
print("최솟값 : ",a.min())
print("평균값 : ",a.mean())

a = [0.57439702 0.56681213 0.32449629 0.52144776 0.68445481 0.92878485
 0.3129446  0.81468706 0.70778983 0.12444609]
최댓값 :  0.9287848524772997
최솟값 :  0.12444608602127216
평균값 :  0.5560260437499279


In [20]:
a = np.array([0,10,20,40,60,80])
b = np.array([0,20])
list1 =[]
for i in a:
    if i in b: #x in y조건문을 활용하여 True와 False를 구분하였다.
        list1.append('True')
    else:
        list1.append("False")
print(list1)

['True', 'False', 'True', 'False', 'False', 'False']
